use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Kalanhall/Specs.git'

target 'KLHomeService_Example' do
  pod 'KLHomeService', :path => '../'
  pod 'KLHomeServiceInterface'

  target 'KLHomeService_Tests' do
    inherit! :search_paths

    
  end
end
