use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Kalanhall/Specs.git'

target 'KLHomeService_Example' do
  pod 'KLHomeService', :path => '../'

  target 'KLHomeService_Tests' do
    inherit! :search_paths

    
  end
end
